language: ruby
bundler_args: --without development

rvm:
	- 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
	- rbx-18mode
  - rbx-19mode
  - jruby-19mode
  - jruby-head


allow_failures:
	- rvm: 1.8.7
	- rvm: jruby
	- rvm: rbx-18mode
	- rvm: ree
