language: ruby
bundler_args: --without development

rvm:
	- 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode

branches:
	only:
		- master
		- 0.x.x

matrix:
	allow_failures:
		- rvm: rbx-18mode
		- rvm: 1.8.7
